---
# This playbook deploys a single node k8s cluster on debian
- name: Install Kubernetes master
  hosts: master
  remote_user: root
  roles:
    - node-config
    - master
    - cluster-apps-default
    - cluster-apps-custom