---
- name: Bootstrap Tasks
  hosts: 
    - nodes
    - masters
  become: yes
  gather_facts: False
  roles:
    - node-config

- name: Install and init master
  hosts: masters
  become: yes
  roles:
    - master

- name: Install and join nodes
  become: yes
  hosts: nodes
  roles:
    - worker

- name: deploy apps
  hosts: masters
  become: yes
  roles:
    - cluster-apps-default
    - cluster-apps-custom
    - post-install