- name: add Docker apt-key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add Docker's APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present
    filename: 'docker'

- name: "Install Docker with specific version"
  apt:
    pkg:
      - docker-ce={{ docker_version }}
    state: present

- name: adding existing user "{{ ansible_user }}" to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start docker service
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes