- name: 'YUM - async task'
  yum:
    name: docker-io
    state: present
  async: 1000
  poll: 0
  register: yum_sleeper

- name: 'YUM - check on async task'
  async_status:
    jid: "{{ yum_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30


- name: Disable swap
  shell: swapoff -a

- name: Disable swap permanently (modify /etc/fstab)
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    backup: yes
    replace: '#\1'

- name: set net.ipv4.ip_forward to 1
  retries: 2
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: "Install kubeadm and dependencies"
  apt:
    pkg:
      - kubelet={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
    state: present