- name: create the 'k8s' user
  user: 
    name: k8s 
    append: yes 
    state: present 
    createhome: yes 
    shell: /bin/bash

- name: allow 'k8s' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'k8s ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the k8s user
  authorized_key: 
    user: k8s 
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: adding existing user k8s to group docker
  user:
    name: k8s
    groups: docker
    append: yes