# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: pv-volume-manual
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/opt/k8s-manual"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local
  local:
    path: /opt/local-k8s-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s02
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer