- name: "Install dependencies"
  apt:
    pkg:
      - apt-transport-https
      - python-apt
      - python-minimal
      - python3-pip
      - ca-certificates
      - gnupg2
      - software-properties-common
      - vim
      - git
      - sudo
      - lvm2
      - open-iscsi
    state: present
