- name: copy elasticsearch files
  copy:
    src: elasticsearch/
    dest: "{{ template_dir }}/elasticsearch/"

- name: template and copy kibana ingress
  template:
    src: kibana/kibana-ingress.j2
    dest: "{{ template_dir }}/elasticsearch/kibana-ingress.yml"
    mode: 0775

# deploy elasticsearch crd
- name: "kubectl apply {{ template_dir }}/elasticsearch/elastic-crd.yml"
  shell: "kubectl apply -n logging -f {{ template_dir }}/elasticsearch/elastic-crd.yml"

# deploy kibana crd
- name: "kubectl apply {{ template_dir }}/elasticsearch/kibana-crd.yml"
  shell: "kubectl apply -n logging -f {{ template_dir }}/elasticsearch/kibana-crd.yml"

# deploy kibana ingress
- name: "kubectl apply {{ template_dir }}/elasticsearch/kibana-ingress.yml"
  shell: "kubectl apply -n logging -f {{ template_dir }}/elasticsearch/kibana-ingress.yml"

# deploy filebeat
- name: "kubectl apply {{ template_dir }}/elasticsearch/filebeat.yml"
  shell: "kubectl apply -n logging -f {{ template_dir }}/elasticsearch/filebeat.yml"