- name: create template dir
  file:
    path: "{{ template_dir }}/grafana"
    state: directory
    mode: '0755'

- name: template and copy grafana values
  template:
    src: grafana/values.j2
    dest: "{{ template_dir }}/grafana/values.yml"
    mode: 0775

# helm template
- name: helm template grafana
  shell: |
    helm template \
      --name grafana \
      --namespace monitoring \
      "{{ template_dir }}/charts/stable/grafana" \
      -f "{{ template_dir }}/grafana/values.yml" \
      > "{{ template_dir }}/grafana/grafana-templated.yml"
  args:
    executable: /bin/bash

# deploy grafana
- name: kubectl apply "{{ template_dir }}/grafana/grafana-templated.yml"
  shell: "kubectl apply -n monitoring -f {{ template_dir }}/grafana/grafana-templated.yml"