- name: copy over files
  copy:
    src: kube-state-metrics/
    dest: "{{ template_dir }}/kube-state-metrics/"

# helm template
- name: helm template kube-state-metrics
  shell: |
    helm template --name kube-state-metrics \
      "{{ template_dir }}/charts/stable/kube-state-metrics" \
      -f "{{ template_dir }}/kube-state-metrics/values.yml" \
      > "{{ template_dir }}/kube-state-metrics/kube-state-metrics-templated.yml"
  args:
    executable: /bin/bash

# deploy kube-state-metrics
- name: kubectl apply "{{ template_dir }}/kube-state-metrics/kube-state-metrics-templated.yml"
  shell: "kubectl apply -n kube-system -f {{ template_dir }}/kube-state-metrics/kube-state-metrics-templated.yml"