- import_tasks: nfs-client-provisioner.yml
- import_tasks: metallb.yml
- import_tasks: traefik.yml
# TODO fix metrics server
#- import_tasks: metrics-server.yml
- import_tasks: kube-state-metrics.yml
- import_tasks: prometheus.yml
- import_tasks: grafana.yml
- import_tasks: elastic-operator.yml
- import_tasks: elasticsearch.yml