- name: copy over files
  copy:
    src: metrics-server/
    dest: "{{ template_dir }}/metrics-server/"

# helm template
- name: helm template metrics-server
  shell: |
    helm template --name metrics-server \
      "{{ template_dir }}/charts/stable/metrics-server" \
      -f "{{ template_dir }}/metrics-server/values.yml" \
      > "{{ template_dir }}/metrics-server/metrics-server-templated.yml"
  args:
    executable: /bin/bash

# deploy metrics-server
- name: kubectl apply "{{ template_dir }}/metrics-server/metrics-server-templated.yml"
  shell: "kubectl apply -n kube-system -f {{ template_dir }}/metrics-server/metrics-server-templated.yml"