- name: copy over files
  copy:
    src: metrics-server/
    dest: /tmp/cluster-install/metrics-server/

# helm template
- name: helm template metrics-server
  shell: |
    helm template --name metrics-server \
      /tmp/cluster-install/charts/stable/metrics-server \
      -f /tmp/cluster-install/metrics-server/values.yml \
      > /tmp/cluster-install/metrics-server/metrics-server-templated.yml
  args:
    executable: /bin/bash

# deploy metrics-server
- name: kubectl apply /tmp/cluster-install/metrics-server/metrics-server-templated.yml
  shell: "kubectl apply -f /tmp/cluster-install/metrics-server/metrics-server-templated.yml"