- name: create template dir
  file:
    path: "{{ template_dir }}/nfs-client-provisioner"
    state: directory
    mode: '0755'

- name: template and copy nfs-client-provisioner values
  template:
    src: nfs-client-provisioner/values.j2
    dest: "{{ template_dir }}/nfs-client-provisioner/values.yml"
    mode: 0775

# helm template
- name: helm template nfs-client-provisioner
  shell: |
    helm template \
      --name nfs-client-provisioner \
      "{{ template_dir }}/charts/stable/nfs-client-provisioner" \
      -f "{{ template_dir }}/nfs-client-provisioner/values.yml" \
      > "{{ template_dir }}/nfs-client-provisioner/nfs-client-provisioner-templated.yml"
  args:
    executable: /bin/bash

# deploy nfs-client-provisioner
- name: kubectl apply "{{ template_dir }}/nfs-client-provisioner/nfs-client-provisioner-templated.yml"
  shell: "kubectl apply -f {{ template_dir }}/nfs-client-provisioner/nfs-client-provisioner-templated.yml"

- pause:
    seconds: 20