- name: copy files
  copy:
    src: prometheus/
    dest: "{{ template_dir }}/prometheus/"

# helm template
- name: helm template prometheus
  shell: |
    helm template \
      --name prometheus \
      --namespace monitoring \
      "{{ template_dir }}/charts/stable/prometheus" \
      -f "{{ template_dir }}/prometheus/values.yml" \
      > "{{ template_dir }}/prometheus/prometheus-templated.yml"
  args:
    executable: /bin/bash

# deploy prometheus
- name: kubectl apply "{{ template_dir }}/prometheus/prometheus-templated.yml"
  shell: "kubectl apply -n monitoring -f {{ template_dir }}/prometheus/prometheus-templated.yml"