- name: create template dir
  file:
    path: "{{ template_dir }}/traefik"
    state: directory
    mode: '0755'

- name: template and copy traefik values
  template:
    src: traefik/values.j2
    dest: "{{ template_dir }}/traefik/values.yml"
    mode: 0775

# helm template
- name: helm template traefik
  shell: |
    helm template \
      --name traefik \
      --namespace traefik \
      "{{ template_dir }}/charts/stable/traefik" \
      -f "{{ template_dir }}/traefik/values.yml" \
      > "{{ template_dir }}/traefik/traefik-templated.yml"
  args:
    executable: /bin/bash

# deploy traefik
- name: kubectl apply "{{ template_dir }}/traefik/traefik-templated.yml"
  shell: "kubectl apply -n traefik -f {{ template_dir }}/traefik/traefik-templated.yml"