- name: download helm zip
  get_url:
    url: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: "{{ template_dir }}/helm.tar.gz"
    mode: 0440

- name: "Wait until the file {{ template_dir }}/helm.tar.gz is present"
  wait_for:
    path: "{{ template_dir }}/helm.tar.gz"
    timeout: 20
    delay: 2
    msg: "Timeout to find file {{ template_dir }}/helm.tar.gz"

- name: unarchive helm archive
  unarchive:
    src: "{{ template_dir }}/helm.tar.gz"
    dest: "{{ template_dir }}/"
    remote_src: yes

- name: Move helm binary to /usr/local/bin
  command: "mv {{ template_dir }}/linux-amd64/helm /usr/local/bin/helm"

- name: make helm binary executable
  file: dest=/usr/local/bin/ mode=+x

# download official helm charts to /tmp
- git:
    repo: 'https://github.com/helm/charts.git'
    dest: "{{ template_dir }}/charts"