- import_tasks: create-folders.yml
- import_tasks: build-cluster.yml
- import_tasks: helm-config.yml
- import_tasks: flannel.yml
- import_tasks: namespaces.yml
- import_tasks: create-local-storage.yml