- name: add Docker apt-key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add Docker's APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present
    filename: 'docker'

- name: install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: add remote user to group docker
  command: usermod -aG docker {{ansible_user}}

- name: Start docker service
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes